version: '3.7'

services:
    redis:
        container_name: redis
        image: redislabs/rejson:latest
        ports:
          - 6379:6379

    backend:
        stdin_open: true
        image: neukai/chore-backend
        container_name: backend
        ports:
         - 5000:5000
        links:
          - redis

    frontend:
        stdin_open: true
        image: neukai/chore-frontend
        container_name: frontend
        ports:
         - 8080:80
