apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: neukai/chore-backend
          imagePullPolicy: Always
          name: backend
          env:
            - name: REDIS_URL
              value: "redis"
          ports:
            - containerPort: 5000
